name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Build with Maven
        run: mvn -B package --no-transfer-progress
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: '**/target/*.jar'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
