vault.backend=hashicorp
vault.hashi.uri=https://vault.internal:8200
vault.hashi.auth.method=approle
vault.hashi.auth.approle.role-id=${VAULT_HASHI_AUTH_APPROLE_ROLE_ID:}
vault.hashi.auth.approle.secret-id=${VAULT_HASHI_AUTH_APPROLE_SECRET_ID:}
vault.hashi.engine.mount=cashu
